# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: davide.scovotto@conio.com
author_name: ScovottoDavide
cloud_provider: none
preset_name: production
project_name: AlgoDigitalMarketplace-frontend

