# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: davide.scovotto@conio.com
author_name: ScovottoDavide
cloud_provider: none
contract_name: algo_digital_marketplace
deployment_language: python
preset_name: production
project_name: AlgoDigitalMarketplace

